# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Fib_m2 = 1
Fib_m1 = 2
sum = Fib_m1
i = 3
l = 0
temp = Fib = Fib_m1 + Fib_m2
while (temp <= 4000000):
	if (l == 2) :
		print(Fib)
		sum = sum + Fib
		l = 0
	else :
		l = l + 1

	temp = Fib + Fib_m1
	if (temp <= 4000000):
		# Renew parameters for Fib number in the next cycle
		Fib_m2 = Fib_m1
		Fib_m1 = Fib
		Fib = temp
		i = i + 1

print(sum)

# answer is 4613732
